# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'

target 'outdoor-life' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for outdoor-life

  target 'outdoor-lifeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'outdoor-lifeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
